import math
a =10
b =-5
c = 4.3
d = 3
print("a=",a)
print("b=",b)
print("c=",c)
print("d=",d)

z = math.ceil(a)
print('math.ceil(',c,') =',z)
z =math.fabs(b)
print('math.fabs(',b,') =',z)
z =math.factorial(a)
print('math.factorial(',a,') =',z)
z = math.floor(c)
print('math.floor(',c,') =',z)
z = math.exp(b)
print('math.exp(',b,') =',z)
z = math.log2(a)
print('math.log2(',a,') =',z)
z = math.log10(a)
print('math.log10(',d,', ',a,') =',z)
z = math.log(d,a)
print('math.log(',d,', ',a,') =',z)
z = math.pow(a,d)
print('math.pow(',a,', ',d,') =',z)
z = math.sqrt(a)
print('math.sqrt(',a,') =',z)
